update daft to 0.1.5
Fixes rustdoc failure from:

```
error[E0557]: feature has been removed
 --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/daft-0.1.3/src/lib.rs:1:30
  |
1 | #![cfg_attr(doc_cfg, feature(doc_auto_cfg))]
  |                              ^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
  = note: merged into `doc_cfg`
```